version: '3.1'

services:
  nodejs:
    image: node:latest
    command: >
      sh -c "npm install --prefix ./home &&
             node /home/src/index.js"
    volumes:
      - ./:/home/
    ports:
      - "8080:8080"
