version: '3.1'

services:
  nodejs:
    image: node:latest
    command: >
      sh -c "npm install --prefix ./home &&
             node /home/src/index.js"
    volumes:
      - ./:/home/
    ports:
      - "8080:8080"
  nginx:
    image: nginx:1.15-alpine
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./config/certbot/conf:/etc/letsencrypt
      - ./config/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    links:
      - nodejs
    command: "/bin/sh -c 'while :; do sleep 12h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:
      - ./config/certbot/conf:/etc/letsencrypt
      - ./config/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --force-renewal; sleep 48h & wait $${!}; done;'"